"""Auto-generate IEEE paper tables from frozen + post-hoc result CSVs.

Regenerate after any upstream change (tables are build artifacts):

    python scripts/v4_paper_tables.py

Inputs are read-only; outputs go to paper/tables/*.tex and are \\input by
paper/main.tex. Every table carries its provenance as a LaTeX comment.
"""

from pathlib import Path

import pandas as pd

PROJECT = Path(__file__).resolve().parent.parent
TABLES = PROJECT / "paper" / "tables"

POSTHOC = PROJECT / "results" / "v4" / "posthoc"
FROZEN = PROJECT / "results" / "final_robustness"


def esc(text: str) -> str:
    return str(text).replace("_", "\\_")


def write(name: str, provenance: str, body: str) -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    path = TABLES / name
    path.write_text(f"% AUTO-GENERATED by scripts/v4_paper_tables.py\n"
                    f"% Provenance: {provenance}\n"
                    f"% DO NOT EDIT BY HAND; regenerate instead.\n{body}")
    print(f"wrote {path.relative_to(PROJECT)}")


def table_posthoc_per_seed() -> None:
    """Pooled false-latch rate + conditional detection per training seed."""
    summary = pd.read_csv(POSTHOC / "per_seed_summary.csv")
    pooled = summary[summary["study"] == "PartB"].copy()
    # Pooled Part B rows have family == NaN (grouped by training seed only).
    pooled = pooled[pooled["family"].isna()]
    lines = ["\\begin{tabular}{lcccc}",
             "\\toprule",
             "Training seed & runs & false-latch rate [95\\% CI] & "
             "clean starts & cond. detection \\\\",
             "\\midrule"]
    for _, row in pooled.sort_values("training_seed").iterrows():
        lines.append(
            f"{int(row['training_seed'])} & {int(row['n_runs'])} & "
            f"${row['false_latch_rate']:.3f}$ "
            f"[{row['false_latch_wilson_lo']:.3f}, "
            f"{row['false_latch_wilson_hi']:.3f}] & "
            f"{int(row['n_clean_start'])} & "
            f"${row['cond_post_event_entry_given_clean']:.3f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write("tab_posthoc_per_seed.tex",
          "results/v4/posthoc/per_seed_summary.csv (PartB pooled rows, POST-HOC)",
          "\n".join(lines) + "\n")


def table_envelope_relabel() -> None:
    """Preregistered envelope labels beside post-hoc conditional labels."""
    relabeled = pd.read_csv(POSTHOC / "envelope_relabelled_posthoc.csv")
    lines = ["\\begin{tabular}{lllll}",
             "\\toprule",
             "Condition & preregistered & latches & cond. detection & "
             "post-hoc \\\\",
             "\\midrule"]
    for _, row in relabeled.iterrows():
        lines.append(
            f"{esc(row['condition_label'])} & {esc(row['preregistered_classification'])} & "
            f"{int(row['posthoc_n_pre_event_latch_of_15'])}/15 & "
            f"${row['posthoc_cond_pooled_detection']:.2f}$ & "
            f"{esc(row['posthoc_conditional_classification'])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write("tab_envelope_relabel.tex",
          "results/v4/posthoc/envelope_relabelled_posthoc.csv (POST-HOC)",
          "\n".join(lines) + "\n")


def table_frozen_detection() -> None:
    """Frozen Part B pooled detection (unchanged preregistered anchor)."""
    detection = pd.read_csv(FROZEN / "detection_wilson_intervals.csv")
    pooled = detection[detection["training_seed"] == "pooled"]
    pooled = pooled[pooled["endpoint"] == "sensor_fault_detection_probability"]
    lines = ["\\begin{tabular}{llll}",
             "\\toprule",
             "Family & condition & successes & pooled detection [95\\% CI] \\\\",
             "\\midrule"]
    for _, row in pooled.iterrows():
        lines.append(
            f"{esc(row['family'])} & {esc(row['condition_label'])} & "
            f"{int(row['successes'])}/{int(row['trials'])} & "
            f"${row['probability']:.3f}$ "
            f"[{row['wilson95_low']:.3f}, {row['wilson95_high']:.3f}] \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write("tab_frozen_detection.tex",
          "results/final_robustness/detection_wilson_intervals.csv pooled rows (FROZEN)",
          "\n".join(lines) + "\n")


def main() -> None:
    table_posthoc_per_seed()
    table_envelope_relabel()
    table_frozen_detection()


if __name__ == "__main__":
    main()
